# TRY THIS QUERY TO FIND UNUSED INDEXES:

SELECT st.TABLE_SCHEMA, 
       st.TABLE_NAME, 
       st.INDEX_NAME
FROM 
   information_schema.STATISTICS st
LEFT JOIN 
   information_schema.INDEX_STATISTICS idx
ON idx.INDEX_NAME = st.INDEX_NAME
AND idx.TABLE_NAME = st.TABLE_NAME
AND idx.TABLE_SCHEMA = st.TABLE_SCHEMA
WHERE
   (idx.INDEX_NAME IS NULL OR idx.ROWS_READ = 0)
AND st.NON_UNIQUE = 1
AND st.TABLE_SCHEMA not in('mysql')
ORDER BY 1, 2, 3;
